export enum KindEnum {
	NO_KIND_DEF = 'NO_KIND_DEF',
	VAR = 'VAR',
	PARAM = 'PARAM',
	FUNCTION = 'FUNCTION',
	FIELD = 'FIELD',
	ARRAY_TYPE = 'ARRAY_TYPE',
	STRUCT_TYPE = 'STRUCT_TYPE',
	ALIAS_TYPE = 'ALIAS_TYPE',
	SCALAR_TYPE = 'SCALAR_TYPE',
	UNIVERSAL = 'UNIVERSAL',
}
