export enum TypeEnum {
  NO_KIND_DEF_ = "NO_KIND_DEF",
  VAR_ = "VAR",
  PARAM_ = "PARAM",
  FUNCTION_ = "FUNCTION",
  FIELD_ = "FIELD",
  ARRAY_TYPE_ = "ARRAY_TYPE",
  STRUCT_TYPE_ = "STRUCT_TYPE",
  ALIAS_TYPE_ = "ALIAS_TYPE",
  SCALAR_TYPE_ = "SCALAR_TYPE",
  UNIVERSAL_ = "UNIVERSAL",
}
