import { TOKENS, Tokens } from '../Lexical/utils';

export enum States {
	P = 'P',
	LDE = 'LDE',
	DE = 'DE',
	DF = 'DF',
	DT = 'DT',
	T = 'T',
	DC = 'DC',
	LI = 'LI',
	LP = 'LP',
	B = 'B',
	LDV = 'LDV',
	LS = 'LS',
	DV = 'DV',
	S = 'S',
	E = 'E',
	LV = 'LV',
	L = 'L',
	R = 'R',
	Y = 'Y',
	F = 'F',
	LE = 'LE',
	ID = 'ID',
	TRUE = 'TRUE',
	FALSE = 'FALSE',
	CHR = 'CHR',
	STR = 'STR',
	NUM = 'NUM',
	PLINHA = 'PLINHA',
	M = 'M',
	U = 'U',
	IDD = 'IDD',
	IDU = 'IDU',
	NB = 'NB',
	MF = 'MF',
	MC = 'MC',
	NF = 'NF',
	MT = 'MT',
	ME = 'ME',
	MW = 'MW',
}

export const RULES_LEFT: States[] = [
	States.P,
	States.LDE,
	States.LDE,
	States.DE,
	States.DE,
	States.T,
	States.T,
	States.T,
	States.T,
	States.T,
	States.DT,
	States.DT,
	States.DT,
	States.DC,
	States.DC,
	States.DF,
	States.LP,
	States.LP,
	States.B,
	States.LDV,
	States.LDV,
	States.LS,
	States.LS,
	States.DV,
	States.LI,
	States.LI,
	States.S,
	States.S,
	States.U,
	States.U,
	States.M,
	States.M,
	States.M,
	States.M,
	States.M,
	States.M,
	States.M,
	States.E,
	States.E,
	States.E,
	States.L,
	States.L,
	States.L,
	States.L,
	States.L,
	States.L,
	States.L,
	States.R,
	States.R,
	States.R,
	States.Y,
	States.Y,
	States.Y,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.F,
	States.LE,
	States.LE,
	States.LV,
	States.LV,
	States.LV,
	States.IDD,
	States.IDU,
	States.ID,
	States.TRUE,
	States.FALSE,
	States.CHR,
	States.STR,
	States.NUM,
	States.NB,
	States.MF,
	States.MC,
	States.NF,
	States.MT,
	States.ME,
	States.MW,
];

export const RULES_RIGHT = [
	1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 9, 8, 4, 5, 3, 10, 5, 3, 4, 2, 1, 2, 1, 5, 3, 1, 1, 1, 6, 9, 9, 7,
	8, 2, 4, 2, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 1, 1, 2, 2, 2, 2, 3, 5, 2, 2, 1, 1, 1,
	1, 1, 3, 1, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
];

export const ACTIONS_TABLE_COLUMNS: (Tokens | States)[] = [
	Tokens.INTEGER,
	Tokens.CHAR,
	Tokens.BOOLEAN,
	Tokens.STRING,
	Tokens.TYPE,
	Tokens.EQUALS,
	Tokens.ARRAY,
	Tokens.LEFT_SQUARE,
	Tokens.RIGHT_SQUARE,
	Tokens.OF,
	Tokens.STRUCT,
	Tokens.LEFT_BRACES,
	Tokens.RIGHT_BRACES,
	Tokens.SEMI_COLON,
	Tokens.COLON,
	Tokens.FUNCTION,
	Tokens.LEFT_PARENTHESIS,
	Tokens.RIGHT_PARENTHESIS,
	Tokens.COMMA,
	Tokens.VAR,
	Tokens.IF,
	Tokens.ELSE,
	Tokens.WHILE,
	Tokens.DO,
	Tokens.BREAK,
	Tokens.CONTINUE,
	Tokens.AND,
	Tokens.OR,
	Tokens.LESS_THAN,
	Tokens.GREATER_THAN,
	Tokens.LESS_OR_EQUAL,
	Tokens.GREATER_OR_EQUAL,
	Tokens.EQUAL_EQUAL,
	Tokens.NOT_EQUAL,
	Tokens.PLUS,
	Tokens.MINUS,
	Tokens.TIMES,
	Tokens.DIVIDE,
	Tokens.PLUS_PLUS,
	Tokens.MINUS_MINUS,
	Tokens.NOT,
	Tokens.DOT,
	Tokens.ID,
	Tokens.TRUE,
	Tokens.FALSE,
	Tokens.CHARACTER,
	Tokens.STRINGVAL,
	Tokens.NUMERAL,
	Tokens.EOF,
	States.PLINHA,
	States.P,
	States.LDE,
	States.DE,
	States.T,
	States.DT,
	States.DC,
	States.DF,
	States.LP,
	States.B,
	States.LDV,
	States.LS,
	States.DV,
	States.LI,
	States.S,
	States.U,
	States.M,
	States.E,
	States.L,
	States.R,
	States.Y,
	States.F,
	States.LE,
	States.LV,
	States.IDD,
	States.IDU,
	States.ID,
	States.TRUE,
	States.FALSE,
	States.CHR,
	States.STR,
	States.NUM,
	States.NB,
	States.MF,
	States.MC,
	States.NF,
	States.MT,
	States.ME,
	States.MW,
];
